# Generated by Django 3.2.6 on 2021-09-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_work', '0006_alter_company_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='letter',
            field=models.TextField(null=True),
        ),
    ]
