# Generated by Django 3.2.6 on 2022-05-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_work', '0008_alter_application_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='employee_count',
            field=models.IntegerField(default=1),
        ),
    ]
